#SPDX-License-Identifier: MIT-0
---
- name: Install RRDCacheD packages
  ansible.builtin.apt:
    name: "{{ rrdcached_packages }}"
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Install configuration file
  ansible.builtin.template:
    src: etc/default/rrdcached.j2
    dest: /etc/default/rrdcached
    owner: root
    group: root
    mode: '0644'
  notify: Restart RRDCacheD

- name: Ensure RRDCacheD journal directory has correct ownership
  ansible.builtin.file:
    path: "{{ rrdcached_journal_path }}"
    owner: "{{ rrdcached_daemon_user }}"
    group: "{{ rrdcached_daemon_group }}"
    state: directory
  notify: Restart RRDCacheD
